#!/usr/bin/perl

# FASTA retrieval test

use warnings;

BEGIN {
  require File::Basename;
  require Cwd;

  push @INC, Cwd::abs_path((File::Basename::fileparse(__FILE__))[1] . '../lib');
}

use WWW::UniProt qw(get_protein);
use Test::Simple tests => 1;

# Network FASTA
$fasta_net = get_protein 'Q8JJY4'; # Grab FASTA
$fasta_net =~ s/^>.*//; # Drop comments
$fasta_net =~ s/\r?\n//g; # Drop newlines

# Local FASTA
$fasta_loc = join '', <DATA>;
$fasta_loc =~ s/^>.*//;
$fasta_loc =~ s/\r?\n//g;

ok($fasta_net eq $fasta_loc, 'Retrieve FASTA');

__DATA__
>tr|Q8JJY4|Q8JJY4_SFAVA Putative myosine-like protein OS=Spodoptera frugiperda ascovirus 1a PE=4 SV=1
MRLTLENFRIFGGRTELTFSDTGVTLLSAPSGTGKTTVLDAIEFVLFNAPSSTTVAGNYE
NPRTRTTAVTLEIGNVRVKRTRRPNTVTCTFTDTGVQLVEQECEEAIRRIFGYRLTDPIR
DVVLRISGCDDYDTYVQGVKDYGKIQRSELQRLTGELEGYERMQCQIPSVAKPTKVNNGP
RPQQVDVKAITGEVKRLEDLHRGTRDGLSLMKFKLCAIQQELQTTIEKKNEEEAYLFQLA
GSSDYDHTMKRYDVTRLNDELNAIQCSRSRLHERLVGTNKDLDNAWANVVTLCEQIDIAK
ERRGTALKELRMLGYREDDELDYDPGHVEATEKHGCLLKSQLRQHVDALTDCDDTLSKLP
HDCVNNVRWPTNCELIDGKCTDYETAKREYQDTLSVLRQRWQSVKSSLLTARDNLSTALK
KCERDFPHVSCDNIESLKHTASNALRKRAERYEQRLHDYLAAGDDDGQCSMPASFAKKIL
ALLRDVRAGRAVEENVIVELYEAYSNSVKLECELKNVKEAIEVENERLEMIDMLSLAFTT
NCKRYTTHVKISQCEHSIRSLPDTSNVKQAYRARSTVSNCDDVLRECSSRLKAYLRKRDD
LYVECAEVQRVQTEIDVRRDELADELSVMNERNSLVHSIEELTKRVSHLNESAERLNVDI
AQATVSVHEQSRLHADPLRRWSVPRT
